name: educode
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  flutter_fortune_wheel: ^1.3.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  get: ^4.6.6
  firebase_auth: ^5.1.3
  flutter_signin_button: ^2.0.0
  ionicons: ^0.2.2
  http: ^1.2.2
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  cloud_firestore: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/coding.png
    - lib/assets/contra.png
    - lib/assets/fondo.jpg
    
  # Uncomment and add your custom fonts here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
